version: '3'

# Define services
services:

  # App Service
  app:
    container_name: gameObjectBackend-app
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: docker/golang/Dockerfile
    ports:
      - "7019:7019" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped   
    environment: 
      GO_ENV: production
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - gameObjectBackend
  
  gameObjectBackend-mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: gameObjectBackend-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./sql/gameObjectBackend.sql:/docker-entrypoint-initdb.d/gameObjectBackend.sql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3317:3306"    
    networks:
      - gameObjectBackend

networks:
  gameObjectBackend:   