version: '3'

services:
  game-mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: gameObjectBackend-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./sql/gameObjectBackend.sql:/docker-entrypoint-initdb.d/gameObjectBackend.sql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3317:3306"    
    networks:
      - game

networks:
  game: