[http_server]
host = "0.0.0.0"
port = 7019

[database]
type = "mysql"
host = "0.0.0.0"
port = 3306
username = "root"
password = "root"
dbname = "gameObjectBackend"

[token_manager]
secret = "WHOCANINHERITEDTHEDREAM0515"