[http_server]
host = "0.0.0.0"
port = 7019

[database]
type = "mysql"
host = "localhost"
port = 3317
username = "root"
password = "root"
dbname = "gameObjectBackend"

[token_manager]
secret = "IJUSTHOPEWECANTOGETHER"